java_test(
    name = "WebhookResponseProducerModuleTest",
    srcs = ["WebhookResponseProducerModuleTest.java"],
    test_class = "test.java.slugchat.api.producer.WebhookResponseProducerModuleTest",
    deps = [
        "//main/java/slugchat/api/producer",
        "//main/java/slugchat/api/models",
        "//main/java/slugchat/mybatis",
        "//main/java/slugchat/constants",
        "//main/java/slugchat/api/annotations",
         "@com_google_guava_guava//jar",
               "@com_google_inject_guice//jar",
               "@com_google_inject_extensions_guice_testlib//jar",
        "@junit_junit//jar",
        
        "@ai_api_libai//jar",
    ],
)
