package(
  default_visibility = ["//visibility:public"],
)


java_library(
    name = "models",
    srcs = glob(["*.java"]),
    deps = [
        "@com_fasterxml_jackson_core_jackson_annotations//jar"
    ]
)