#java_library(
#    name = "lorabit",
#    srcs = glob(["*.java"]),
#    deps = [
#        ":test_proto_java",
#        "@com_google_inject_guice//jar", 
#        "@com_google_inject_extensions//jar", 
#    ]
#)
#
#java_binary(
#    name = "bin",
#    runtime_deps = [":lorabit"],
#    main_class = "Main",
#)
#
#proto_library(
#    name = "test_proto",
#    srcs = ["test.proto"]
#)
#
#java_proto_library(
#    name = "test_proto_java",
#    deps = ["test_proto"]
#)