
java_test(
    name = "ChatbotResponseProducerModuleTest",
    srcs = glob(["*.java"]),
    test_class = "test.java.slugchat.mobile.service.implementation.producers.ChatbotResponseProducerModuleTest",
    deps = [
        "//main/java/slugchat/mobile/service/dao",
        "//main/java/slugchat/mobile/service/domain",
        "//main/java/slugchat/mobile/service/implementation",
        "//main/java/slugchat/mobile/service/implementation/producers",
        "//main/java/slugchat/mobile/service/implementation/annotations",
        "//main/java/slugchat/mobile/service/mapper",
         "@com_google_guava_guava//jar",
               "@com_google_inject_guice//jar",
               "@com_google_inject_extensions_guice_testlib//jar",
        "@junit_junit//jar",
    ],
)
