

java_test(
    name = "DialogflowResultProducerModuleTest",
    srcs = ["DialogflowResultProducerModuleTest.java"],
    test_class = "test.java.slugchat.mobile.service.implementation.producers.DialogflowResultProducerModuleTest",
    deps = [
        "//slugchat/protos:mobile_java_proto",
        "//main/java/slugchat/mybatis/dao:dao",
        "//main/java/slugchat/mybatis/domain:domain",
        "//main/java/slugchat/mobile/service/implementation",
        "//main/java/slugchat/mobile/service/implementation/producers",
        "//main/java/slugchat/mobile/service/implementation/annotations",
        "//main/java/slugchat/mybatis/mapper:mapper",
         "@com_google_guava_guava//jar",
               "@com_google_inject_guice//jar",
               "@com_google_inject_extensions_guice_testlib//jar",
        "@junit_junit//jar",
        
        "@ai_api_libai//jar",
    ],
)


java_test(
    name = "ChatbotResponseProducerModuleTest",
    srcs = ["ChatbotResponseProducerModuleTest.java"],
    test_class = "test.java.slugchat.mobile.service.implementation.producers.ChatbotResponseProducerModuleTest",
    deps = [
        "//slugchat/protos:mobile_java_proto",
        "//main/java/slugchat/mybatis/dao:dao",
        "//main/java/slugchat/mybatis/domain:domain",
        "//main/java/slugchat/mobile/service/implementation",
        "//main/java/slugchat/mobile/service/implementation/producers",
        "//main/java/slugchat/mobile/service/implementation/annotations",
        "//main/java/slugchat/mybatis/mapper:mapper",
         "@com_google_guava_guava//jar",
               "@com_google_inject_guice//jar",
               "@com_google_inject_extensions_guice_testlib//jar",
        "@junit_junit//jar",
    ],
)


