java_library(
    name = "producer",
    srcs = glob(["*.java"]),
    deps = [
          "//main/java/kidschat/api/annotations",
          "//third_party:com_google_inject_guice",
          "//third_party:com_google_guava_guava",
    ]
)