java_library(
    name = "implementation",
    srcs = glob(["*.java"]),
    deps = [
        "@org_mybatis_mybatis//jar",
        "@org_mybatis_mybatis_guice//jar",
        "@com_google_inject_guice//jar", 
        "@com_google_inject_extensions_guice_servlet//jar",
    ]
)