package(
    default_visibility = ["//visibility:public"],
)

java_library(
    name = "mapper",
    srcs = glob(["*.java"]),
    deps = [
        "//main/java/slugchat/mybatis/domain:domain",
        "@org_mybatis_mybatis//jar",
    ],
)
