
package(
  default_visibility = ["//visibility:public"],
)


java_library(
    name = "annotations",
    srcs = glob(["*.java"]),
    deps = [
        "//third_party:com_google_inject_guice",
    ],
)